# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Netaggr < Formula
  desc "Network aggregator/summarizer"
  homepage "https://github.com/ebarkie/netaggr"
  version "1.3.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ebarkie/netaggr/releases/download/v1.3.9/netaggr_Darwin_x86_64.tar.gz"
      sha256 "5c2aed92f17c2397fc27b95fcee4c41e8a64b4b4b5e99e46345a94ebca02b014"

      def install
        bin.install "netaggr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ebarkie/netaggr/releases/download/v1.3.9/netaggr_Darwin_arm64.tar.gz"
      sha256 "8a23b40c39c7590c88d5b9903fcbdb5663fa537f98b0f808ec93600ba0d93953"

      def install
        bin.install "netaggr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ebarkie/netaggr/releases/download/v1.3.9/netaggr_Linux_x86_64.tar.gz"
        sha256 "9750ee072512e9bbec3d9a6ed87cfe3202b66e9a8e29f25b1ead1126d7183849"

        def install
          bin.install "netaggr"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ebarkie/netaggr/releases/download/v1.3.9/netaggr_Linux_arm64.tar.gz"
        sha256 "3b4fc03c26e3e805ba94b39e7a75ccb0e1766aa434e535bda48c2edc357d9f51"

        def install
          bin.install "netaggr"
        end
      end
    end
  end
end
